pool:
  vmImage: 'ubuntu-latest'
services:
  redis:
    image: redis
    ports:
      - 6379:6379

steps:
- task: GoTool@0
  inputs:
    version: '1.13.5'
- script: cd scripts/aelf-node && bash start.sh
- script: |
    bash build.sh
  displayName: 'test'