jobs:
- job: build_all_window
  displayName: Build all tasks (window)
  pool:
    vmImage: 'windows-2019'
  steps:
  - task: GoTool@0
    inputs:
      version: '1.13.5'
  - task: UseDotNet@2
    displayName: 'Install .NET Core SDK'
    inputs:
      version: 3.1.101
  - powershell: ./scripts/aelf-node/start-window.ps1
    displayName: 'deploy a full node'
  - powershell: ./build.ps1
    displayName: 'Test'

- job: build_all_linux
  displayName: Build all tasks (Linux)
  pool:
    vmImage: 'ubuntu-latest'
  services:
    redis:
      image: redis
      ports:
        - 6379:6379
  steps:
  - task: GoTool@0
    inputs:
      version: '1.13.5'
  - script: cd scripts/aelf-node && bash start.sh
  - script: |
      bash build.sh
    displayName: 'Test'